---
title: "Obesity and GLP-1s"
format: 
  html:
    fontsize: 11px
    mainfont: "Arial"
---

This file blaah blah blah

df_included_practices <- included_practices() 




```{r}
#| label: load-packages
#| include: false

library(dplyr)
library(readr)
library(here)
library(glue)
library(tidyr)
library(stringr)
library(scales) ## format label_number
library(gt) ## gt table
library(ggplot2)
library(lubridate) # interval
library(arrow)
```

```{r}
#| label: import_design_files

source(here("analysis", "design", "design.r"))
source(here("analysis", "functions", "functions.r"))
source(here("analysis", "functions", "utils.r"))


## create save folder
fs::dir_create(here("data"))
fs::dir_create(here(
  "output",
  "icb",
  "nonprescribing"
))
```

```{r}
#| label: run-opr-and-qof
#| eval: false
source(here("analysis", "0_get-qof.r"))
source(here("analysis", "1_opr_extract.r"))
```

```{r}
#| label: import-data
#| include: false

#### practice level orlistat data
op_df_orlistat_practice <- read_parquet(here::here(
  "data",
  "op_df_orlistat.parquet"
))

#### practice level tirzepatide data
op_df_tirzepatide_practice <- read_parquet(here::here(
  "data",
  "op_df_tirzepatide.parquet"
))

### ccgs from practice
op_df_ccgs <- read_parquet(here::here(
  "data",
  "op_df_ccgs.parquet"
))


op_df_chemical_names_orlistat <- read_parquet(
  here("data", "op_df_bnf_orlistat.parquet")
) |>
  select(-year_month)

op_df_chemical_names_tirzepatide <- read_parquet(
  here("data", "op_df_bnf_tirzepatide.parquet")
) |>
  select(-year_month)

op_df_practice_open_info <- read_parquet(
  here("data", "op_df_gp_practices.parquet")
)

op_df_practice_list_size <- read_parquet(
  here("data", "op_df_practice_statistics.parquet")
)

op_df_region_names <- read_parquet(
  here("data", "op_df_regional_teams.parquet")
)

op_df_stp_names <- read_parquet(
  here("data", "op_df_stp_names.parquet")
)

df_qof_ob <- read_csv(here::here("data", "qof", "prevalence.csv")) |>
  filter(year == "2024-25") |>
  select(practice_code, register)
```


```{r}
#| label: tirzepatide_clean
#| include: false

op_df_tirzepatide_practice <- op_df_tirzepatide_practice |>
  filter(grepl("0.6ml", bnf_name)) |>
  mutate(
    strength = gsub("[^0-9/.]", "", bnf_name),
    strength = gsub("2.4", "", strength),
    strength = gsub("/", "mg / ", strength),
    strength = glue("{strength}ml")
  ) |>
  select(-sha, -pct)
```

```{r}
#| label: orlistat_clean
#| include: false
op_df_orlistat_practice <- op_df_orlistat_practice |>
  filter(grepl("120mg", bnf_name)) |>
  mutate(
    strength = gsub("\\D", "", bnf_name),
    strength = glue("{strength}mg")
  ) |>
  select(-sha, -pct)
```


```{r}
#| label: filter_practices
#| include: false

### join practice open dates to practice list size by code / practice
included_practice_status <- function() {
  df <- op_df_practice_open_info |>
    full_join(op_df_practice_list_size, by = join_by(code == practice)) |>
    ## create closed status by month
    ## close date is after end of month, join date is before month, leave_provider_date is after end of month)
    mutate(
      month_status = case_when(
        !is.na(close_date) & close_date <= rollforward(month) ~ "closed",
        (!is.na(join_provider_date) &
          join_provider_date >= month) ~ "not opened",
        !is.na(leave_provider_date) &
          (leave_provider_date <= rollforward(month)) ~ "left provider",
        .default = "open"
      )
    ) |>
    left_join(
      op_df_ccgs |> select(code, regional_team_id, stp_id),
      by = join_by(ccg_id == code)
    )
}


included_practices <- function() {
  included_practice_status() |>
    # exclude unopen, dormat and pratcices with list_size < 1000
    filter(
      month_status == "open",
      status_code_label != "Dormant",
      total_list_size >= 1000
    ) |>
    mutate(prac_name = str_to_title(name)) |>
    select(code, month, prac_name, total_list_size, ccg_id) |>
    left_join(
      op_df_ccgs |> select(code, regional_team_id, stp_id),
      by = join_by(ccg_id == code)
    )
}
```

```{r}
#| label: filter_practices_data_checks
#| eval: false

df_included_practice_status <- included_practice_status()

### number of practices in dfs
op_df_practice_open_info |> distinct(code) |> nrow()

op_df_practice_list_size |>
  distinct(practice) |>
  nrow()

op_df_included_practice_status |> distinct(code) |> nrow()

## count practices with missing list size (i.e. not in df_practice_list_size)
op_df_included_practice_status |>
  filter(is.na(total_list_size)) |>
  distinct(code) |>
  nrow()


## count practices with missing setting (i.e. not in df_practice_open_info)
op_df_included_practice_status |>
  filter(is.na(setting)) |>
  distinct(code) |>
  nrow()

#identify practices with missing setting (i.e. not in df_practice_open_info)
op_df_included_practice_status |>
  filter(is.na(setting)) |>
  count(month, by = month_status)

op_df_included_practice_status |>
  filter(is.na(setting)) |>
  distinct(code) |>
  left_join(
    op_df_practice_list_size |>
      summarise(
        mean_list_size = mean(total_list_size),
        n_months = n(),
        last_date = (max(month)),
        .by = practice
      ),
    by = join_by(code == practice)
  ) |>
  select(code, mean_list_size, n_months, last_date)


#identify active practices with missing list size (i.e. not in df_practice_list_size)
df_missing_active <- op_df_included_practice_status |>
  filter(is.na(total_list_size), status_code_label == "Active") |>
  select(code, name, stp_id)

op_df_included_practice_status |>
  filter(is.na(total_list_size), status_code_label == "Active") |>
  count(stp_id) |>
  arrange(-n)

# df with only practices in df_practice_list_size
df_included_practice_status_withlist <- op_df_included_practice_status |>
  filter(!(is.na(total_list_size)), !is.na(setting))

## check 15 practices lost from df_practice_list_size (monthly counts of df_included_practice_status_withlist == monthly counts of df_included_practice_status_withlist should be TRUE)
df_included_practice_status_withlist |>
  count(month) |>
  full_join(op_df_practice_list_size |> count(month)) |>
  nrow() ==
  df_included_practice_status_withlist |> count(month) |> nrow()


### check status by month
df_included_practice_status_withlist |>
  count(month, .by = month_status)

## check status at fetch date
df_fetch_status <- df_included_practice_status_withlist |>
  filter(month == as.Date(end_date)) |>
  count(month_status)


### practices that don't make it to end date
df_end_practices <- df_included_practice_status_withlist |>
  filter(month == as.Date(end_date)) |>
  select(code, name, stp_id, status_code_label)

df_all_practices <- df_included_practice_status_withlist |>
  select(code, name, stp_id, status_code_label)

df_all_practices |>
  anti_join(df_end_practices) |>
  distinct() |>
  count(status_code_label)

## by active type
df_all_practices |>
  anti_join(df_end_practices) |>
  filter(status_code_label == "Active") |>
  distinct()


## check all practices have a status at fetch date (Total rows in df_included_practice_status_withlist == total number of statuses in df_fetch_status should be TRUE )
df_included_practice_status_withlist |>
  filter(month == as.Date(end_date)) |>
  nrow() ==
  df_fetch_status |>
    pull(n) |>
    sum()


### check discordants
df_included_practice_status_withlist |>
  filter(
    month_status == "open",
    month == as.Date(end_date)
  ) |>
  count(status_code_label)

# identify non-active practices at fetch date
df_non_actice <- df_included_practice_status_withlist |>
  filter(
    status_code_label != "Active",
    month_status == "open",
    month == as.Date(end_date)
  ) |>
  select(code, name, status_code_label, stp_id, total_list_size) |>
  arrange(stp_id)

df_included_practice_status_withlist |>
  filter(
    status_code_label != "Active",
    month_status == "open",
    month == as.Date(end_date)
  ) |>
  count(status_code_label, .by = stp_id) |>
  arrange(-n)


### how many practices are lost by filtering by >1000 patients
df_included_practice_status_withlist |>
  filter(
    month == as.Date(end_date),
    total_list_size >= 1000
  )

# identify non-active practices at fetch date
df_included_practice_status_withlist |>
  filter(
    month == as.Date(end_date),
    total_list_size >= 1000
  ) |>
  filter(
    status_code_label != "Active",
    month_status == "open",
    month == as.Date(end_date)
  ) |>
  count(status_code_label, .by = stp_id) |>
  arrange(-n)


#### final dataset (remove dormant practices)
df_included_practice_status_withlist |>
  filter(
    month == as.Date(end_date),
    total_list_size >= 1000
  ) |>
  filter(
    status_code_label != "Dormant",
    month_status == "open",
    month == as.Date(end_date)
  ) |>
  count(status_code_label, .by = stp_id) |>
  arrange(-n) |>
  pull(n) |>
  sum()
```



```{r}
#| label: combine_data_sets
#| include: false

combine_data <- function(drug) {
  df <- get(glue("op_df_{drug}_practice"))

  df_strength <- df |>
    distinct(strength)

  df_included_practices <- included_practices() |>
    crossing(df_strength)

  ### add chemical name from df_chemical_names_
  df2 <- df |>
    inner_join(
      get(glue("op_df_chemical_names_{drug}")),
      by = join_by(bnf_code == presentation_code)
    )
  ### warn if rows added or removed
  if (nrow(df2) != nrow(df)) {
    print(glue("df mismatch bnf: df {nrow(df)}, df2 {nrow(df2)}"))
  }

  df2 <- df2 |>
    summarise(
      items = sum(items),
      chemical = last(chemical),
      .by = c(month, regional_team, stp, practice, strength)
    )

  ### add practice info from df_included_practices
  df3 <- df2 |>
    right_join(
      df_included_practices,
      by = join_by(month, strength, practice == code)
    )

  df3 <- df3 |>
    fill(c(regional_team, stp), .direction = "downup", .by = practice) |>
    fill(chemical, .direction = "downup") |>
    ungroup() |>
    mutate(
      regional_team = case_when(
        is.na(regional_team) ~ regional_team_id,
        .default = regional_team
      ),
      stp = case_when(is.na(stp) ~ stp_id, .default = stp),
      items = replace_na(items, 0)
    ) |>
    select(-ccg_id, -regional_team_id)

  df3
}
```


```{r}
#| label: non-prescribing practices
#| include: false

df_nonprescribed <- function(drug, ...) {
  combine_data(drug) |>
    summarise(
      items = sum(items),
      total_list_size = mean(total_list_size),
      .by = c(month, practice, ...)
    ) |>
    filter(items == 0)
}

missed_population <- function(drug, ...) {
  df <- df_nonprescribed(drug, ...) |>
    summarise(
      total_list_size = sum(total_list_size),
      .by = c(month, ...)
    )
}

nonprescribing_practices <- function(drug, ...) {
  df <- df_nonprescribed(drug, ...) |>
    count(month, .by = ...) %>%
    rename(n_practices = n)
  df
}

### check non expected icb
# combine_data("tirzepatide") |> anti_join(icbs, by = join_by(stp == code))

##### compare number of practices not prescribing
np_tirz <- nonprescribing_practices("tirzepatide") |>
  mutate(drug = "tirzepatide")
np_orli <- nonprescribing_practices("orlistat") |> mutate(drug = "orlistat")

np_comparison <- np_tirz |> bind_rows(np_orli)

### by stp
np_tirz_stp <- nonprescribing_practices("tirzepatide", stp) |>
  mutate(drug = "tirzepatide")
np_orli_stp <- nonprescribing_practices("orlistat", stp) |>
  mutate(drug = "orlistat")

np_comparison_stp <- np_tirz_stp |> bind_rows(np_orli_stp)


np_comparison_plot_stp <- np_comparison_stp |>
  ggplot(aes(x = month, y = n_practices, colour = drug)) +
  facet_wrap(vars(stp)) +
  geom_line()


ggsave(
  filename = here::here(
    "output",
    "icb",
    "nonprescribing",
    "nonprescribing.png"
  ),
  np_comparison_plot_stp,
  dpi = 800,
  width = 60,
  height = 30,
  units = "cm"
)


##### last month non-prescribing practices
np_end <- np_tirz |>
  filter(month == as.Date(end_date)) |>
  mutate(stp = "England")
np_end_stp <- np_tirz_stp |> filter(month == as.Date(end_date))
#check ICB sum total matches England total
# sum(np_end_stp |> pull(n)) == np_end |> pull(n)
np_end <- np_end |>
  bind_rows(np_end_stp)


### compare number of patients from non-prescribing practices
mp_tirz <- missed_population("tirzepatide") |> mutate(drug = "tirzepatide")
mp_orli <- missed_population("orlistat") |> mutate(drug = "orlistat")

mp_comparison <- mp_tirz |> bind_rows(mp_orli)


mp_comparison_plot <- mp_comparison |>
  ggplot(aes(x = month, y = total_list_size, colour = drug)) +
  geom_line()

### compare number of patients from non-prescribing practices by ICB (stp)
mp_tirz_stp <- missed_population("tirzepatide", stp) |>
  mutate(drug = "tirzepatide")
mp_orli_stp <- missed_population("orlistat", stp) |> mutate(drug = "orlistat")

mp_comparison_stp <- mp_tirz_stp |> bind_rows(mp_orli_stp)


mp_comparison_plot_stp <- mp_comparison_stp |>
  ggplot(aes(x = month, y = total_list_size, colour = drug)) +
  facet_wrap(vars(stp)) +
  geom_line()

##### last month non-prescribing practices population
mp_end <- mp_tirz |>
  filter(month == as.Date(end_date)) |>
  mutate(stp = "England")
mp_end_stp <- mp_tirz_stp |> filter(month == as.Date(end_date))
#check ICB sum total matches England total
# sum(mp_end_stp |> pull(total_list_size)) == mp_end |> pull(total_list_size)
mp_end <- mp_end |>
  bind_rows(mp_end_stp)

### join practices and population
end_info <- mp_end |>
  inner_join(np_end) |>
  select(drug, stp, n_practices, total_list_size) |>
  arrange(-n_practices)

### identify practices that didn't prescribe
df_nonprescribed("tirzepatide") |>
  filter(month == as.Date(end_date)) |>
  select(practice, total_list_size) %>%
  left_join(
    op_df_practice_open_info |> select(code, name, ccg_id),
    by = join_by(practice == code)
  ) |>
  left_join(
    op_df_ccgs |> select(code, regional_team_id, stp_id),
    by = join_by(ccg_id == code)
  ) |>
  select(practice, name, stp_id, regional_team_id, total_list_size)
```

```{r}
#| label: dormant
#| eval: false
dormant_practices <- function(status_label) {
  included_practice_status() |>
    # exclude unopen, dormat and pratcices with list_size < 1000
    filter(
      month_status == "open",
      status_code_label == status_label,
      total_list_size >= 1000
    ) |>
    select(code, month, total_list_size, ccg_id) |>
    left_join(
      op_df_ccgs |> select(code, regional_team_id, stp_id),
      by = join_by(ccg_id == code)
    )
}


combine_data_dormant <- function(drug, status_label) {
  df <- get(glue("op_df_{drug}_practice"))

  df_strength <- df |>
    distinct(strength)

  df_included_practices <- dormant_practices(status_label) |>
    crossing(df_strength)

  ### add chemical name from df_chemical_names_
  df2 <- df |>
    inner_join(
      get(glue("op_df_chemical_names_{drug}")),
      by = join_by(bnf_code == presentation_code)
    )
  ### warn if rows added or removed
  if (nrow(df2) != nrow(df)) {
    print(glue("df mismatch bnf: df {nrow(df)}, df2 {nrow(df2)}"))
  }

  df2 <- df2
  ### add practice info from df_included_practices
  df3 <- df2 |>
    right_join(
      df_included_practices,
      by = join_by(month, strength, practice == code)
    ) %>%
    select(-bnf_name)

  df3 |>
    fill(c(regional_team, stp), .direction = "downup", .by = practice) |>
    fill(chemical, .direction = "downup") |>
    ungroup() |>
    mutate(
      regional_team = case_when(
        is.na(regional_team) ~ regional_team_id,
        .default = regional_team
      ),
      stp = case_when(is.na(stp) ~ stp_id, .default = stp),
      items = replace_na(items, 0)
    ) |>
    select(-bnf_code, -ccg_id, -regional_team_id)
}

df_dormant <- combine_data_dormant("tirzepatide", "Dormant")

## number of dormant practices 60
df_dormant |> distinct(practice) |> nrow()

### any prescribing
df_dormant <- df_dormant |>
  summarise(items = sum(items), .by = c(month, practice))

df_dormant |> count(month) %>% rename(n_practices = n)
df_dormant_nil <- df_dormant |>
  filter(items == 0) |>
  count(month) %>%
  rename(n_non_prescribing = n)
df_dormant_any <- df_dormant |>
  filter(items != 0) |>
  count(month) %>%
  rename(n_prescribing = n)
df_dormant_all <- df_dormant |> count(month) %>% rename(n_practices = n)

df_dormant_months <- df_dormant_all |>
  left_join(df_dormant_nil) |>
  left_join(df_dormant_any)


#### retired
df_retired <- combine_data_dormant("tirzepatide", "Retired")

## number of retired practices 222
df_retired |> distinct(practice) |> nrow()

### any prescribing
df_retired <- df_retired |>
  summarise(items = sum(items), .by = c(month, practice))

df_retired |> count(month) %>% rename(n_practices = n)
df_retired_nil <- df_retired |>
  filter(items == 0) |>
  count(month) %>%
  rename(n_non_prescribing = n)
df_retired_any <- df_retired |>
  filter(items != 0) |>
  count(month) %>%
  rename(n_prescribing = n)
df_retired_all <- df_retired |> count(month) %>% rename(n_practices = n)

df_retired_months <- df_retired_all |>
  left_join(df_retired_nil) |>
  left_join(df_retired_any)
```

```{r}
#| label: qof_datasets
#| include: false

df_qof_region <- read_csv(here::here("data", "qof", "geography.csv"))


df_included_practices <- included_practices()

df_included_practices_qof_period <- df_included_practices |>
  filter(month >= start_date_qof, month <= end_date_qof)

df_included_practices_qof_period_n <- df_included_practices_qof_period |> nrow()
## 73218

df_included_practices_qof <- df_included_practices_qof_period |>
  inner_join(df_qof_ob, by = join_by(code == practice_code))


df_included_practices_qof |> nrow() #73166

### practice_months dropped (52)
df_included_practices_qof_period_n - df_included_practices_qof |> nrow()

### dropped practices (12)
df_included_practices_qof_dropped <- df_included_practices_qof_period |>
  anti_join(df_qof_ob, by = join_by(code == practice_code)) |>
  distinct(code, stp_id)

## dropped from included practices
df_included_practices_qof_period |>
  inner_join(df_included_practices_qof_dropped) |>
  distinct(code, stp_id)
### so we cannot aggregate the QOF data and then join. We will have to join on practice first.
```


```{r}
#| label: icb-level
#| include: false

qof_icb_names <- df_qof_region |>
  filter(year == "2024-25") |>
  distinct(icb_ods_code, icb_name)

practice_level_data <- function(drug, ...) {
  ## aggregate to stp level
  df <- combine_data(drug) |>
    left_join(op_df_stp_names, by = join_by(stp == code)) |>
    left_join(
      qof_icb_names,
      by = join_by(stp == icb_ods_code)
    ) |>
    mutate(
      icb_code = stp,
      icb_name = case_when(
        name ==
          "NHS CENTRAL EAST INTEGRATED CARE BOARD" ~ "NHS Central East Integrated Care Board",
        name ==
          "NHS ESSEX INTEGRATED CARE BOARD" ~ "NHS Essex Integrated Care Board",
        name ==
          "NHS HAMPSHIRE AND ISLE OF WIGHT INTEGRATED CARE BOARD" ~ "NHS Hampshire and Isle of Wight Integrated Care Board",
        name ==
          "NHS NORFOLK AND SUFFOLK INTEGRATED CARE BOARD" ~ "NHS Norfolk and Suffolk Integrated Care Board",
        name ==
          "NHS SURREY AND SUSSEX INTEGRATED CARE BOARD" ~ "NHS Surrey and Sussex Integrated Care Board",
        name ==
          "NHS THAMES VALLEY INTEGRATED CARE BOARD" ~ "NHS Thames Valley Integrated Care Board",
        name ==
          "NHS WEST AND NORTH LONDON INTEGRATED CARE BOARD" ~ "NHS West and North London Integrated Care Board",
        .default = icb_name
      )
    ) |>
    summarise(
      items = sum(items),
      total_list_size = mean(total_list_size),
      rateper1000 = items / total_list_size * 1000,
      .by = c(month, practice, prac_name, ...)
    )

  df
}


england_level_data <- function(df_in, drug, ...) {
  ## aggregate to stp level
  df <- df_in |>
    summarise(
      items = sum(items),
      total_list_size = sum(total_list_size),
      rateper1000 = items / total_list_size * 1000,
      .by = c(month, ...)
    )
}

practice_level_data_qof <- function(df_in, drug, ...) {
  ## aggregate to stp level
  df <- df_in |>
    filter(month >= start_date_qof, month <= end_date_qof) |>
    inner_join(
      df_qof_ob,
      by = join_by(practice == practice_code)
    ) |>
    mutate(rateper1000register = items / register * 1000) |>
    arrange(month, practice, prac_name, ...)
}


england_level_data_qof <- function(df_in, drug, ...) {
  ## aggregate to stp level
  df <- df_in |>
    summarise(
      items = sum(items),
      total_list_size = sum(total_list_size),
      register = sum(register),
      rateper1000 = items / total_list_size * 1000,
      rateper1000register = items / register * 1000,
      .by = c(month, ...)
    )
}


outputs_func <- function(drug, ...) {
  df1 <- practice_level_data(drug, icb_code, icb_name, regional_team, ...)
  df1_qof <- practice_level_data_qof(
    df1,
    drug,
    icb_code,
    icb_name,
    regional_team,
    ...
  )
  df2 <- england_level_data(df1, drug, icb_code, icb_name, regional_team, ...)
  df2_qof <- england_level_data_qof(
    df1_qof,
    drug,
    icb_code,
    icb_name,
    regional_team,
    ...
  )
  df3 <- england_level_data(df1, drug, ...)
  df3_qof <- england_level_data_qof(df1_qof, drug, ...)

  list(
    practice = df1,
    icb = df2,
    england = df3,
    practice_qof = df1_qof,
    icb_qof = df2_qof,
    england_qof = df3_qof
  )
}

tirzepatide_dfs <- outputs_func("tirzepatide")
tirzepatide_strength_dfs <- outputs_func("tirzepatide", strength)
orlistat_dfs <- outputs_func("orlistat")
orlistat_strength_dfs <- outputs_func("orlistat", strength)
```

```{r}
#| label: icb_checks
#| eval: false

### check each stp for each month has a row for each strength and list size is consistent (tibble should be empty)
orlistat_strength_dfs$icb |>
  count(month, icb_code, total_list_size) |>
  filter(n != orlistat_strength_dfs$icb |> distinct(strength) |> nrow())

### check each stp for each month has a row for each strength and list size is consistent (tibble should be empty)
tirzepatide_strength_dfs$icb |>
  count(month, icb_code, total_list_size) |>
  filter(n != tirzepatide_strength_dfs$icb |> distinct(strength) |> nrow())

### consistency of ICB name (compare tirzepatide_df to df_qof_region)
qof_icb_check <- tirzepatide_dfs$practice_qof |>
  inner_join(
    df_qof_region |> filter(year == "2024-25"),
    by = join_by(practice == practice_code)
  ) |>
  distinct(icb_name.x, icb_name.y) |>
  reframe(
    previous_icb = icb_name.y,
    current_icb = icb_name.x,
    match = str_to_title(icb_name.x) == str_to_title(icb_name.y)
  ) |>
  filter(match == FALSE) |>
  arrange(current_icb)

df_icb_rename <- tirzepatide_dfs$practice_qof |>
  inner_join(
    df_qof_region |> filter(year == "2024-25"),
    by = join_by(practice == practice_code)
  ) |>
  distinct(icb_name.x, icb_name.y) |>
  reframe(
    previous_icb = icb_name.y,
    current_icb = icb_name.x,
    match = str_to_title(icb_name.x) == str_to_title(icb_name.y)
  )


### consistency of ICB name (internally in tirzepatide_df)
tirzepatide_dfs$practice_qof |>
  distinct(icb_name, practice) |>
  add_count(practice) |>
  filter(n > 1)
### no practices have more than one ICB attached

### check consistentcy of icb names in QOF 2024-25
df_qof_region |>
  filter(year == "2024-25") |>
  distinct(icb_ods_code, icb_name) |>
  count(icb_ods_code) |>
  filter(n > 1)
```



```{r}
#| label: practices_counts

df_practice_counts <- tirzepatide_dfs$practice |>
  count(month)
##check is the same for orlistat
df_practice_counts_2 <- orlistat_dfs$practice |>
  count(month)

identical(df_practice_counts, df_practice_counts_2)

## check strengths
df_practice_counts <- tirzepatide_strength_dfs$practice |>
  filter(strength == "5mg / 0.6ml") |>
  count(month)
##check is the same for orlistat
df_practice_counts_2 <- orlistat_strength_dfs$practice |>
  count(month)

identical(df_practice_counts, df_practice_counts_2)

all_practices <- tirzepatide_dfs$practice |> distinct(practice) |> nrow()
```





```{r}
#| label: save_dfs
#| eval: false

# number of practices
write_rds(
  all_practices,
  here("data", "all_practices.rds")
)

write_parquet(
  df_practice_counts,
  here("data", "df_practice_counts.parquet")
)

# tirzepatide per 1000 (England, icb, practices)
write_parquet(
  tirzepatide_dfs$england,
  here("data", "df_tirzepatide_england.parquet")
)

write_parquet(
  tirzepatide_strength_dfs$england,
  here("data", "df_tirzepatide_england_strength.parquet")
)

write_parquet(
  tirzepatide_dfs$icb,
  here("data", "df_tirzepatide_icb.parquet")
)

write_parquet(
  tirzepatide_strength_dfs$icb,
  here("data", "df_tirzepatide_icb_strength.parquet")
)

write_parquet(
  tirzepatide_dfs$practice,
  here("data", "df_tirzepatide_practice.parquet")
)

write_parquet(
  tirzepatide_strength_dfs$practice,
  here("data", "df_tirzepatide_practice_strength.parquet")
)


# orlistat per 1000 (England, icb, practices)
write_parquet(
  orlistat_dfs$england,
  here("data", "df_orlistat_england.parquet")
)

write_parquet(
  orlistat_strength_dfs$england,
  here("data", "df_orlistat_england_strength.parquet")
)

write_parquet(
  orlistat_dfs$icb,
  here("data", "df_orlistat_icb.parquet")
)

write_parquet(
  orlistat_strength_dfs$icb,
  here("data", "df_orlistat_icb_strength.parquet")
)

write_parquet(
  orlistat_dfs$practice,
  here("data", "df_orlistat_practice.parquet")
)

write_parquet(
  orlistat_strength_dfs$practice,
  here("data", "df_orlistat_practice_strength.parquet")
)

# tirzepatide per 1000 QOF Obesity register (England, icb, practices)
write_parquet(
  tirzepatide_dfs$england_qof,
  here("data", "df_tirzepatide_england_qof.parquet")
)

write_parquet(
  tirzepatide_strength_dfs$england_qof,
  here("data", "df_tirzepatide_england_strength_qof.parquet")
)

write_parquet(
  tirzepatide_dfs$icb_qof,
  here("data", "df_tirzepatide_icb_qof.parquet")
)

write_parquet(
  tirzepatide_strength_dfs$icb_qof,
  here("data", "df_tirzepatide_icb_strength_qof.parquet")
)

write_parquet(
  tirzepatide_dfs$practice_qof,
  here("data", "df_tirzepatide_practice_qof.parquet")
)

write_parquet(
  tirzepatide_strength_dfs$practice_qof,
  here("data", "df_tirzepatide_practice_strength_qof.parquet")
)
```